name = "mecha-muse"
compatibility_date = "2023-01-01"
main = "src/index.ts"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "R2"
bucket_name = "sdxl"
preview_bucket_name = "sdxl"
